spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_ecommerce?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: keji283650
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

logging:
  level:
    com.smart.ecommerce: DEBUG
    org.springframework.security: DEBUG
